### ISSUE TITLE
Error during single paper analysis

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/pubtrends#308]
```
[2022-01-17 20:57:13,492: INFO/ForkPoolWorker-2] Searching for a publication with doi=10.1063/5.0021420
[2022-01-17 20:57:13,510: INFO/ForkPoolWorker-2] Analyzing 1 paper(s) from Pubmed
[2022-01-17 20:57:13,511: INFO/ForkPoolWorker-2] Expanding related papers by references
[2022-01-17 20:57:13,521: INFO/ForkPoolWorker-2] Loading publication data
[2022-01-17 20:57:13,533: ERROR/ForkPoolWorker-2] Task analyze_search_paper[2a6ea877-11e5-4cb4-aa5b-5a17a7be0f52] raised unexpected: SearchError('Nothing found for ids: 0    3338004934539355\n1    3338004934200625\nName: id, dtype: object')
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/pubtrends/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/user/miniconda3/envs/pubtrends/lib/python3.8/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/user/pysrc/celery/tasks_main.py", line 149, in analyze_search_paper
    return _analyze_id_list(
  File "/home/user/pysrc/celery/tasks_main.py", line 123, in _analyze_id_list
    analyzer.analyze_papers(ids, query, topics, test=test, task=task)
  File "/home/user/pysrc/papers/analyzer.py", line 143, in analyze_papers
    raise SearchError(f'Nothing found for ids: {ids}')
pysrc.papers.db.search_error.SearchError: Nothing found for ids: 0    3338004934539355
1    3338004934200625
Name: id, dtype: object
```

**Comment by olegs** [comment]
Similar problem:
```
[2022-01-17 20:59:47,156: INFO/ForkPoolWorker-2] Searching for a publication with doi=10.1016/j.immuni.2020.11.005
[2022-01-17 20:59:47,171: INFO/ForkPoolWorker-2] Analyzing 1 paper(s) from Pubmed
[2022-01-17 20:59:47,172: INFO/ForkPoolWorker-2] Expanding related papers by references
[2022-01-17 20:59:47,199: INFO/ForkPoolWorker-2] Loading publication data
[2022-01-17 20:59:47,211: ERROR/ForkPoolWorker-2] Task analyze_search_paper[6a427f69-e841-48ba-bb80-d9f5aff5838c] raised unexpected: SearchError('Nothing found for ids: 0     3327111834083450\n1     3327111833764576\n2     3327111833986548\n3     3327111833691136\n4     3327111834017346\n5     3327111833854506\n6     3327111834158111\n7     3327111834927082\n8     3327111834688983\n9     3327111834432883\n10    3327111834099898\n11    3327111834367138\n12    3327111834077698\n13    3327111834815556\n14    3327111834685542\n15    3327111834692707\n16    3327111833668142\n17    3327111833968086\n18    3327111834757770\n19    3327111834803388\n20    3327111835032429\n21    3327111833924183\n22    3327111834326766\nName: id, dtype: object')
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/pubtrends/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/user/miniconda3/envs/pubtrends/lib/python3.8/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/user/pysrc/celery/tasks_main.py", line 149, in analyze_search_paper
    return _analyze_id_list(
  File "/home/user/pysrc/celery/tasks_main.py", line 123, in _analyze_id_list
    analyzer.analyze_papers(ids, query, topics, test=test, task=task)
  File "/home/user/pysrc/papers/analyzer.py", line 143, in analyze_papers
    raise SearchError(f'Nothing found for ids: {ids}')
pysrc.papers.db.search_error.SearchError: Nothing found for ids: 0     3327111834083450
1     3327111833764576
2     3327111833986548
3     3327111833691136
4     3327111834017346
5     3327111833854506
6     3327111834158111
7     3327111834927082
8     3327111834688983
9     3327111834432883
10    3327111834099898
11    3327111834367138
12    3327111834077698
13    3327111834815556
14    3327111834685542
15    3327111834692707
16    3327111833668142
17    3327111833968086
18    3327111834757770
19    3327111834803388
20    3327111835032429
21    3327111833924183
22    3327111834326766
Name: id, dtype: object
```
