### ISSUE TITLE
ERROR: could not serialize access due to concurrent update

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/pubtrends#312]
```
Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO pmpublications (abstract, aux, doi, keywords, mesh, pmid, title, type, "year") VALUES ('The experience of eating is inherently multimodal, combining intraoral gustatory, olfactory, and somatosensory signals into a single percept called flavor. As foods and beverages enter the mouth, movements associated with chewing and swallowing activate somatosensory receptors in the oral cavity, dissolve tastants in the saliva to activate taste receptors, and release volatile odorant molecules to retronasally activate olfactory receptors in the nasal epithelium. Human studies indicate that sensory cortical areas are important for intraoral multimodal processing, yet their circuit-level mechanisms remain unclear. Animal models allow for detailed analyses of neural circuits due to the large number of molecular tools available for tracing and neuronal manipulations. In this review, we concentrate on the anatomical and neurophysiological evidence from rodent models toward a better understanding of the circuit-level mechanisms underlying the cortical processing of flavor. While more work is needed, the emerging view pertaining to the multimodal processing of food and beverages is that the piriform, gustatory, and somatosensory cortical regions do not function solely as independent areas. Rather they act as an intraoral cortical hub, simultaneously receiving and processing multimodal sensory information from the mouth to produce the rich and complex flavor experience that guides consummatory behavior.', '{"authors":[{"name":"Samuelsen CL","affiliation":["Department of Anatomical Sciences and Neurobiology, University of Louisville, Louisville, KY, United States"]},{"name":"Vincis R","affiliation":["Department of Biological Science and Program in Neuroscience, Florida State University, Tallahassee, FL, United States"]}],"databanks":[],"journal":{"name":"Frontiers in systems neuroscience"},"language":"eng"}', '10.3389/fnsys.2021.772286', 'chemosensory,cortex,flavor,gustation,multimodal,olfaction,somatosensation', '', 34867223, 'Cortical Hub for Flavor Sensation in Rodents', 'Review', 2021) ON CONFLICT (pmid) DO UPDATE SET title = Excluded.title, abstract = Excluded.abstract, "year" = Excluded."year", keywords = Excluded.keywords, mesh = Excluded.mesh, type = Excluded.type, doi = Excluded.doi, aux = Excluded.aux
RETURNING * was aborted: ERROR: could not serialize access due to concurrent update  Call getNextException to see other errors in the batch.
        at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
        at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1297)
        at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1322)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:465)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
        at org.jetbrains.exposed.sql.statements.InsertStatement.execInsertFunction(InsertStatement.kt:86)
        at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:95)
        at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:12)
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:59)
        ... 16 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: could not serialize access due to concurrent update
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
        ... 25 common frames omitted
2022-05-25 12:10:46,045 INFO [main] o.j.b.p.p.PubmedXMLParser [PubmedXMLParser.kt:462] Storing articles 2001-3000...
```

**Comment by olegs** [comment]
This happened during parallel update - one by crontab schedule, and another process - manual update.
We should avoid parallel updates on the system level with some lock file.
