### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/pubtrends#321]
```
[2022-11-30 08:24:51,804: INFO/MainProcess] Received task: analyze_search_terms[14fe8823-b764-45ca-8e00-1a1ab5a7643a]  
[2022-11-30 08:24:51,806: INFO/ForkPoolWorker-3] Analyzing search query
[2022-11-30 08:24:51,807: INFO/ForkPoolWorker-3] Searching 1000 most cited publications matching rat scenic
[2022-11-30 08:24:53,956: INFO/ForkPoolWorker-3] Found 2 publications in the database
[2022-11-30 08:24:53,957: INFO/ForkPoolWorker-3] Expanding related papers by references
[2022-11-30 08:24:53,963: WARNING/ForkPoolWorker-3] /home/user/miniconda3/envs/pubtrends/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
[2022-11-30 08:24:53,964: WARNING/ForkPoolWorker-3] /home/user/miniconda3/envs/pubtrends/lib/python3.10/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
[2022-11-30 08:24:53,964: WARNING/ForkPoolWorker-3] /home/user/miniconda3/envs/pubtrends/lib/python3.10/site-packages/numpy/core/_methods.py:264: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
[2022-11-30 08:24:53,964: WARNING/ForkPoolWorker-3] /home/user/miniconda3/envs/pubtrends/lib/python3.10/site-packages/numpy/core/_methods.py:222: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
[2022-11-30 08:24:53,965: WARNING/ForkPoolWorker-3] /home/user/miniconda3/envs/pubtrends/lib/python3.10/site-packages/numpy/core/_methods.py:256: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
[2022-11-30 08:24:53,967: ERROR/ForkPoolWorker-3] Task analyze_search_terms[14fe8823-b764-45ca-8e00-1a1ab5a7643a] raised unexpected: ValueError('zero-size array to reduction operation maximum which has no identity')
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/pubtrends/lib/python3.10/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/user/miniconda3/envs/pubtrends/lib/python3.10/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/user/pysrc/celery/tasks_main.py", line 40, in analyze_search_terms
    ids = expand_ids(loader=loader, ids=ids, single_paper=False,
  File "/home/user/pysrc/papers/analysis/expand.py", line 45, in expand_ids
    cit_mean, cit_std = estimate_citations(ids, single_paper, loader,
  File "/home/user/pysrc/papers/analysis/expand.py", line 142, in estimate_citations
    logger.debug(f'Filtered citations min={np.mean(filtered)}, max={np.max(filtered)}, mean={mean}, std={std}')
  File "<__array_function__ internals>", line 180, in amax
  File "/home/user/miniconda3/envs/pubtrends/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 2791, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/home/user/miniconda3/envs/pubtrends/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

**Comment by olegs** [comment]
Another connected stack trace:
```
[2022-11-28 10:57:25,169: INFO/MainProcess] Received task: analyze_search_terms[30d0576d-e220-4a5a-9428-3b402a1933da]  
[2022-11-28 10:57:25,171: INFO/ForkPoolWorker-1] Analyzing search query
[2022-11-28 10:57:25,172: INFO/ForkPoolWorker-1] Searching 1000 most cited publications matching rat scenic
[2022-11-28 10:57:39,225: WARNING/ForkPoolWorker-3] /home/user/pysrc/papers/analyzer.py:228: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor perf
ormance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.df['x'] = tsne_embeddings_2d[:, 0]
[2022-11-28 10:57:39,226: WARNING/ForkPoolWorker-3] /home/user/pysrc/papers/analyzer.py:229: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor perf
ormance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.df['y'] = tsne_embeddings_2d[:, 1]
[2022-11-28 10:57:39,227: ERROR/ForkPoolWorker-3] Task analyze_search_paper[96584252-e074-42a7-894c-8a55fb3984ba] raised unexpected: AttributeError("'NoneType' object has no attribute 'lower'")
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/pubtrends/lib/python3.10/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/user/miniconda3/envs/pubtrends/lib/python3.10/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/user/pysrc/celery/tasks_main.py", line 146, in analyze_search_paper
    return _analyze_id_list(
  File "/home/user/pysrc/celery/tasks_main.py", line 120, in _analyze_id_list
    analyzer.analyze_papers(ids, query, topics, test=test, task=task)
  File "/home/user/pysrc/papers/analyzer.py", line 235, in analyze_papers
    self.progress.info(f'Extracting {topics.lower()} number of topics from papers text and graph similarity',
AttributeError: 'NoneType' object has no attribute 'lower'
```
