### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/pubtrends#322]
```
[2022-11-28 10:57:25,169: INFO/MainProcess] Received task: analyze_search_terms[30d0576d-e220-4a5a-9428-3b402a1933da]  
[2022-11-28 10:57:25,171: INFO/ForkPoolWorker-1] Analyzing search query
[2022-11-28 10:57:25,172: INFO/ForkPoolWorker-1] Searching 1000 most cited publications matching rat scenic
[2022-11-28 10:57:39,225: WARNING/ForkPoolWorker-3] /home/user/pysrc/papers/analyzer.py:228: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor perf
ormance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.df['x'] = tsne_embeddings_2d[:, 0]
[2022-11-28 10:57:39,226: WARNING/ForkPoolWorker-3] /home/user/pysrc/papers/analyzer.py:229: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor perf
ormance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self.df['y'] = tsne_embeddings_2d[:, 1]
[2022-11-28 10:57:39,227: ERROR/ForkPoolWorker-3] Task analyze_search_paper[96584252-e074-42a7-894c-8a55fb3984ba] raised unexpected: AttributeError("'NoneType' object has no attribute 'lower'")
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/pubtrends/lib/python3.10/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/user/miniconda3/envs/pubtrends/lib/python3.10/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/user/pysrc/celery/tasks_main.py", line 146, in analyze_search_paper
    return _analyze_id_list(
  File "/home/user/pysrc/celery/tasks_main.py", line 120, in _analyze_id_list
    analyzer.analyze_papers(ids, query, topics, test=test, task=task)
  File "/home/user/pysrc/papers/analyzer.py", line 235, in analyze_papers
    self.progress.info(f'Extracting {topics.lower()} number of topics from papers text and graph similarity',
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by olegs** [comment]
Cannot reproduce
