### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/pubtrends#324]
```
[2023-02-21 19:33:37,326: ERROR/ForkPoolWorker-9] Task analyze_search_terms[b619861e-69c9-4117-adc4-199bd31ee25e] raised unexpected: AttributeError("'NoneType' object has no attribute 'lower'")
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/pubtrends/lib/python3.10/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/user/miniconda3/envs/pubtrends/lib/python3.10/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/user/pysrc/celery/tasks_main.py", line 48, in analyze_search_terms
    analyzer.analyze_papers(ids, query, topics, test=test, task=current_task)
  File "/home/user/pysrc/papers/analyzer.py", line 235, in analyze_papers
    self.progress.info(f'Extracting {topics.lower()} number of topics from papers text and graph similarity',
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by olegs** [comment]
Cannot reproduce
